#!/bin/bash

#script to generate python module from c++ file

#direct SWIG to the SWIG interface file (.i) and build a new .cpp file
swig -c++ -python -o ats9462_wrap.cpp ats9462_wrapper.i

#note that the include path MUST be for python3.4
#the c++11 file is to prevent errors of the form, 'x... is not a member of std::'
gcc -fPIC -std=c++11 -c ./ats9462_wrap.cpp -o ./ats9462_wrap.o -I/usr/include/python3.4 -std=c++11

#point g++ at the .o file generated in the previous step and the .o file
#generated by compiling the program seperately
g++ -lrt -shared ats9462engine_wrap.o ats9462engine.o -o _ats9462engine.so

#Module will be named 'ats9462
#Note that this must be done using python3
